export const CHANGE_LEAVEVISIBLE = 'leave/CHANGE_LEAVEVISIBLE';
export const CHANGE_LEAVEDATALIST = 'leave/CHANGE_LEAVEDATALIST';
export const CHANGE_HRONEMONTHCLASS = 'leave/CHANGE_HRONEMONTHCLASS';
export const CHANGE_HRONEMONTHTYPE = 'leave/CHANGE_HRONEMONTHTYPE';
export const CHANGE_BUSINESSLEAVETYPE = 'leave/CHANGE_BUSINESSLEAVETYPE';
export const CHANGE_IPSALEAVEREASON = 'leave/CHANGE_IPSALEAVEREASON';
export const CHANGE_BULIST = 'leave/CHANGE_BULIST';
export const CHANGE_DEPLIST = 'leave/CHANGE_DEPLIST';
export const CHANGE_LEAVEPROJ = 'leave/CHANGE_LEAVEPROJ';
export const CHANGE_PROJECTPAGE = 'leave/CHANGE_PROJECTPAGE';
export const CHANGE_BUSONLINEFEEDBACKTYPE =
  'leave/CHANGE_BUSONLINEFEEDBACKTYPE';
