export const CHANGE_KPIWEEKLEAVEDATAANALYSIS =
  'analysis/CHANGE_KPIWEEKLEAVEDATAANALYSIS';

export const CHANGE_WEEKEMPLOYEEDATAANALYSIS =
  'analysis/CHANGE_WEEKEMPLOYEEDATAANALYSIS';

export const CHANGE_KPIWEEKJOBTYPEDATAANALYSIS =
  'analysis/CHANGE_KPIWEEKJOBTYPEDATAANALYSIS';

export const CHANGE_KPIWEEKKPIWHOLEDATAANALYSIS =
  'analysis/CHANGE_KPIWEEKKPIWHOLEDATAANALYSIS';

export const CHANGE_QUERYEMPLOYEECOUNTBYDEPT =
  'analysis/CHANGE_QUERYEMPLOYEECOUNTBYDEPT';

export const CHANGE_QUERYEMPLOYEECOUNTBYWORKCITY =
  'analysis/CHANGE_QUERYEMPLOYEECOUNTBYWORKCITY';

export const CHANGE_QUERYEMPLOYEECOUNTBYJOBCLASS =
  'analysis/CHANGE_QUERYEMPLOYEECOUNTBYJOBCLASS';

export const CHANGE_WEEKLYYEAR = 'analysis/CHANGE_WEEKLYYEAR';
export const CHANGE_WEEKLYCITY = 'analysis/CHANGE_WEEKLYCITY';
export const CHANGE_WEEKLYJOBCLASS = 'analysis/CHANGE_WEEKLYJOBCLASS';
