export const CHANGE_KPIWEEKLEAVEDATAANALYSIS =
  'analysis/CHANGE_KPIWEEKLEAVEDATAANALYSIS';

export const CHANGE_WEEKEMPLOYEEDATAANALYSIS =
  'analysis/CHANGE_WEEKEMPLOYEEDATAANALYSIS';

export const CHANGE_KPIWEEKJOBTYPEDATAANALYSIS =
  'analysis/CHANGE_KPIWEEKJOBTYPEDATAANALYSIS';
