export const CHANGE_EDUCATIONVISIBLE = 'educ/CHANGE_EDUCATIONVISIBLE';
export const CHANGE_BULIST = 'educ/CHANGE_BULIST';
export const CHANGE_DEPLIST = 'educ/CHANGE_DEPLIST';
export const CHANGE_EDUCLIST = 'educ/CHANGE_EDUCLIST';
export const CHANGE_MAGORLIST = 'educ/CHANGE_MAGORLIST';
export const CHANGE_CURRENTPAGE = 'educ/CHANGE_CURRENTPAGE';
