export const CHANGE_ASSIGNMODALVISIBLE = 'personnel/CHANGE_ASSIGNMODALVISIBLE';
export const CHANGE_ADDMODALVISIBLE = 'personnel/CHANGE_ADDMODALVISIBLE';
export const CHANGE_EDITMODALVISIBLE = 'personnel/CHANGE_EDITMODALVISIBLE';
export const CHANGE_DETAilSVISIBLE = 'personnel/CHANGE_DETAilSVISIBLE';
export const CHANGE_INTERVIEWERDATA = 'personnel/CHANGE_INTERVIEWERDATA';
export const CHANGE_RESOURCEMANGEDATA = 'personnel/CHANGE_RESOURCEMANGEDATA';
export const CHANGE_OWNERRANGELIST = 'personnel/CHANGE_OWNERRANGELIST';
export const CHANGE_POSITIONLEVELIST = 'personnel/CHANGE_POSITIONLEVELIST';
export const CHANGE_POSITIONTYPELIST = 'personnel/CHANGE_POSITIONTYPELIST';
export const CHANGE_NEWPROJECTDATALIST = 'personnel/CHANGE_NEWPROJECTDATALIST';
export const CHANGE_ASSIGNINTERVIEWLIST =
  'personnel/CHANGE_ASSIGNINTERVIEWLIST';
